version: '3.1'
services:
    odoo:
      container_name: odoo
    #   image: odoo:latest
      build:
        context: .
        dockerfile: Dockerfile
      # platform: linux/amd64
      volumes:
          - ./addons-extra:/mnt/extra-addons
          - ./config:/etc/odoo
          - odoo-web-data:/var/lib/odoo
      ports:
          - "8069:8069"
      env_file:
          - .env
      mem_limit: 2g
      mem_reservation: .5g
    nginx:
      container_name: nginx
      image: nginx:latest
      restart: unless-stopped
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./nginx/conf:/etc/nginx/conf.d

volumes:
    odoo-web-data:
