version: '3'
services:
    odoo:
      container_name: odoo
    #   image: odoo:latest
      build:
        context: .
        dockerfile: Dockerfile
      # platform: linux/amd64
      volumes:
          - ./addons-extra:/mnt/extra-addons
          - ./config:/etc/odoo
          - odoo-web-data:/var/lib/odoo
      ports:
          - "8069:8069"
      env_file:
          - .env
      mem_limit: 2g
      mem_reservation: 1g 

    nginx:
      container_name: nginx
      image: nginx:latest
      restart: unless-stopped
      ports:
          - 80:80
          - 443:443
      volumes:
        - ./nginx/conf/:/etc/nginx/conf.d/:ro
        - ./certbot/conf:/etc/letsencrypt/ssl  # SSL certificates will be stored here
        - ./certbot/www:/var/www/certbot/:ro  # Webroot for Certbot challenges
        - ./nginx/ssl-dhparams:/etc/ssl/certs  # Diffie-Hellman parameters (for security) 

    certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
    odoo-web-data:
