version: '3'
services:
    odoo:
      container_name: odoo
    #   image: odoo:latest
      build:
        context: .
        dockerfile: Dockerfile
      # platform: linux/amd64
      volumes:
          - ./addons-extra:/mnt/extra-addons
          - ./config:/etc/odoo
          - odoo-web-data:/var/lib/odoo
      ports:
          - "8069:8069"
      env_file:
          - .env
      mem_limit: 2g
      mem_reservation: .5g
    nginx:
      container_name: nginx
      image: nginx:latest
      restart: unless-stopped
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./nginx/conf:/etc/nginx/conf.d
          - ./nginx/ssl:/etc/letsencrypt  # SSL certificates will be stored here
          - ./nginx/html:/var/www/certbot  # Webroot for Certbot challenges
          - ./nginx/ssl-dhparams:/etc/ssl/certs/dhparam.pem  # Diffie-Hellman parameters (for security)
    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - ./nginx/ssl:/etc/letsencrypt
        - ./nginx/html:/var/www/certbot  # Webroot to store challenge files
        - ./nginx/ssl-dhparams:/etc/ssl/certs/dhparam.pem
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
      command: certonly --webroot -w /var/www/certbot -d odoo.robobo.org

volumes:
    odoo-web-data:
