version: '3'
services:
    odoo:
      container_name: odoo
    #   image: odoo:latest
      build:
        context: .
        dockerfile: Dockerfile
      # platform: linux/amd64
      volumes:
          - ./addons-extra:/mnt/extra-addons
          - ./config:/etc/odoo
          - odoo-web-data:/var/lib/odoo
      ports:
          - "8069:8069"
      env_file:
          - .env
      mem_limit: 2g
      mem_reservation: .5g
    nginx:
      container_name: nginx
      image: nginx:latest
      restart: unless-stopped
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./nginx/conf:/etc/nginx/conf.d/:ro
          - ./nginx/ssl:/etc/letsencrypt  # SSL certificates will be stored here
          - ./nginx/html:/var/www/certbot/:ro  # Webroot for Certbot challenges
          - ./nginx/ssl-dhparams:/etc/ssl/certs/dhparam.pem  # Diffie-Hellman parameters (for security)
    certbot:
      image: certbot/certbot
      container_name: certbot
      volumes:
        - certbot-etc:/etc/letsencrypt
        - certbot-var:/var/lib/letsencrypt
        - web-root:/var/www/html
      depends_on:
        - nginx
      command: certonly --webroot --webroot-path=/var/www/html --email it@robobo.org --agree-tos --no-eff-email --staging -d odoo.robobo.org
volumes:
    odoo-web-data:
